---
# Source: cowweb-helm/templates/cowweb.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: cowweb
spec:
  type: LoadBalancer
  selector:
    app: cowweb
  ports:
  - name: http
    port: 80
    targetPort: 8080
    
    
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: production
  name: cowweb
  labels:
    app: cowweb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cowweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cowweb
    spec:
      containers:
      - name: cowweb
        image: hhayakaw/cowweb:v1.0-master-47401c9d5dffab11f49325f3d55a199a58fd2316
        ports:
        - name: api
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 15
          periodSeconds: 20
